### ISSUE TITLE
Your composer requirement for now crash your library

### ISSUE THREAD

**Issue by alexandrmazur96** [the-tinderbox/ClickhouseBuilder#11]
In your composer.json you have `"the-tinderbox/clickhouse-php-client": "^1.0"` which now update to 1.0.**12** (minor!!!) version and require 4 parameters (before was 3) in this class:

 `the-tinderbox/clickhouse-php-client/src/Query/QueryStatistic.php on line 56`

So, maybe you update your library for new code of library or bind version of this requirement library to 1.0.10?

**Comment by evsign** [comment]
Very sorry for this! Fixed and tagged, just update composer)
