### ISSUE TITLE
select query format

### ISSUE THREAD

**Issue by net53** [the-tinderbox/ClickhouseBuilder#13]
$builder->format() works only with formats in which each character in the name is in uppercase
Version 1.2.0

**Comment by evsign** [comment]
Unfortunately with current our clickhouse client, format option cannot work at all. FORMAT JSON is hardcoded in client. When we decide to refactor client for supporting this option we will fix this bag.
Or maybe, if you decide to implement this by yourself we will happy to merge this) Thanks for reply.
