### ISSUE TITLE
SQL Injection Based on 1=1

### ISSUE THREAD

**Issue by ivolkoff** [the-tinderbox/ClickhouseBuilder#14]
my code

```php
$test =  DB::connection('clickhouse')
            ->table('users')
            ->where('id', "105' OR 1=1 OR id='105")
            ->take(50);
die($test->toSql());
```

output:
`SELECT * FROM `users` WHERE `id` = '105' OR 1=1 OR id='105' LIMIT 50`

output all results from the table

https://www.w3schools.com/sql/sql_injection.asp

**Comment by evsign** [comment]
Thanks for issue, fix already in master. Soon we will roll out a new tag.
