### ISSUE TITLE
INSERT  Not working on laravel

### ISSUE THREAD

**Issue by valeriy-efimov** [the-tinderbox/ClickhouseBuilder#15]
Tinderbox\Clickhouse\Exceptions\TransportException  : Host [] returned error: Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected ( before: FORMAT JSON: (at row 2)

"laravel/framework": "5.7.*",
"php": "^7.1.3",

my try
`DB::connection('clickhouse')->using('XXX')->select("INSERT INTO db.table (pid, price, timestamp) VALUES (1, 2, 3)");`

I run this in tabix "INSERT INTO db.table (pid, price, timestamp) VALUES (1, 2, 3)"  and it was executed successfully!

if i try
`DB::connection('clickhouse')->using('XXX')->select("ISELECT pid, price, timestampFROM db.table");` and it was executed successfully but INSERT return error

**Comment by evsign** [comment]
Try to use `public function statement($query, $bindings = [])`
