### ISSUE TITLE
How to use aggregate function in `SELECT`

### ISSUE THREAD

**Issue by iusik** [the-tinderbox/ClickhouseBuilder#16]
I can't understand how to use aggregate function in select.

For example:
```
->select("sum(click_cnt) as click_cnt, zone_id")
```
or this
```
->select("sum(click_cnt) as click_cnt","zone_id")
```
converts to
```
`sum(click_cnt)` as `click_cnt`, `zone_id`
```

But i want:
```
converts to sum(`click_cnt`) as `click_cnt`, `zone_id`
```
How to solve this case?

**Comment by evsign** [comment]
For this you must use `\Tinderbox\ClickhouseBuilder\Query\Expression` or helper function `raw(string $expression)` which wraps expression in needed class object.
Example:
```
->select(raw("count(click_cnt) as click_cnt"), "zone_id");
->select(raw("sum(click_cnt) as click_cnt"), "zone_id");
```
