### ISSUE TITLE
Add support for Laravel 7 & 8

### ISSUE THREAD

**Issue by jairox6x** [the-tinderbox/ClickhouseBuilder#31]
Please add support for L7 and L8.

**Comment by chelsEg** [comment]
> Please add support for L7 and L8.

https://github.com/the-tinderbox/ClickhouseBuilder/pull/32

You need update library **the-tinderbox/ClickhouseBuilder** to version 4.0

**Comment by evsign** [comment]
> > Please add support for L7 and L8.
> 
> #32
> 
> You need update library **the-tinderbox/ClickhouseBuilder** to version 4.0

Already done :)

**Comment by jiaoyang3** [comment]
> > > Please add support for L7 and L8.
> > 
> > 
> > #32
> > You need update library **the-tinderbox/ClickhouseBuilder** to version 4.0
> 
> Already done :)

Can add some examples for Laravel ?
