### ISSUE TITLE
join query error

### ISSUE THREAD

**Issue by jiaoyang3** [the-tinderbox/ClickhouseBuilder#34]
```
$builder->from('table')->join(function ($query) {
    $query->select('column1', 'column2')->from('table2');
}, 'any', 'left', ['column1', 'column2']);

```

The above code execution error!!!

`Fatal error: Uncaught Error: Call to undefined method Tinderbox\ClickhouseBuilder\Query\JoinClause::select() in /Users/jiao/ProjectPhp/test/TestCk/app/1.php:25`

**Comment by vitalcrazz** [comment]
Actually you've missed `subQuery()` method.

It looks more obvious with argument types declarations:

```
$builder->from('table')->join(function (JoinClause $join) {
    $join->subQuery()->select('column1', 'column2')->from('table2');
}, 'any', 'left', ['column1', 'column2']);
```
