### ISSUE TITLE
Testing is failed

### ISSUE THREAD

**Issue by esazykin** [the-tinderbox/ClickhouseBuilder#6]
Hi!

`$ composer test`

There were 2 errors:

1) Tinderbox\ClickhouseBuilder\LaravelIntegrationTest::test_connection_select_async
array_combine(): Both parameters should have an equal number of elements

ClickhouseBuilder/src/Integrations/Laravel/Connection.php:331
ClickhouseBuilder/tests/LaravelIntegrationTest.php:229

2) Tinderbox\ClickhouseBuilder\LaravelIntegrationTest::test_builder_async_get
array_combine(): Both parameters should have an equal number of elements

ClickhouseBuilder/src/Integrations/Laravel/Connection.php:331
ClickhouseBuilder/src/Integrations/Laravel/Builder.php:44
ClickhouseBuilder/tests/LaravelIntegrationTest.php:358

ERRORS!
Tests: 91, Assertions: 360, Errors: 2.

**Comment by evsign** [comment]
all fixed)
