### ISSUE TITLE
Package's tap function is not compatible with laravel's tap function

### ISSUE THREAD

**Issue by mathiasHillmann** [the-tinderbox/ClickhouseBuilder#64]
This package's tap function (https://github.com/the-tinderbox/ClickhouseBuilder/blob/master/src/functions.php#L13) is not compatible with Laravel's tap function (https://github.com/laravel/framework/blob/9.x/src/Illuminate/Support/helpers.php#L300) which causes errors in Laravel if the tap function from this package is registered before Laravel's version (The inverse works fine since this package always sends a callback to the function)

Error example:
```
ArgumentCountError 

  Too few arguments to function tap(), 1 passed in /application/vendor/laravel/framework/src/Illuminate/Support/Facades/Storage.php on line 74 and exactly 2 expected

  at vendor/the-tinderbox/clickhouse-builder/src/functions.php:13
      9▕      * @param callable $callback
     10▕      *
     11▕      * @return mixed
     12▕      */
  ➜  13▕     function tap($value, $callback)
     14▕     {
     15▕         $callback($value);
     16▕ 
     17▕         return $value;

      +20 vendor frames 
  21  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

**Comment by bobanobi4** [comment]
I wrote a pullquest to the author with corrections in this package, he apparently does not see them. Until the author accepted the correction, I created such a file for myself in `composer.json` has prescribed such a script, it copies the file with corrections to the vendor until they are accepted by the author


```"post-autoload-dump": [
            "php -r \"copy(__DIR__.'/app/Helpers/functions.php', __DIR__.'/vendor/the-tinderbox/clickhouse-builder/src/functions.php');\"",
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
```

**Comment by razumnyak** [comment]
#65

**Comment by evsign** [comment]
#65 merged and tagged
